from django.urls import path, re_path
from apps.frontend_compat.views import (
    ManagerDashboardView,
    HrDashboardView,
    AdminDashboardView,
    EmployeeDashboardView,
    DepartmentCompatView,
    DepartmentMembersCompatView,
    DepartmentHeadcountCompatView,
    TeamCompatView,
    TeamMembersCompatView,
    TeamAssignCompatView,
    TeamEmployeeCompatView,
    JobLevelCompatView,
    PositionCompatView,
    RoleCompatView,
    EmployeeRoleCompatView,
    EmployeeDepartmentAssignCompatView,
    FinancialYearCompatView,
    PerformanceCategoryCompatView,
    PermissionCompatView,
    PermissionAssignCompatView,
    PermissionMatrixCompatView,
    EmployeeCompatView,
    EmployeeStatusToggleCompatView,
    CurrentUserProfileCompatView,
    EmployeeAllCompatView,
    EmployeeDirectReportsCompatView,
    EmployeeManagerCompatView,
    AppraisalFormsCompatView,
    AppraisalFormDetailCompatView,
    AppraisalFormCategoriesCompatView,
    AppraisalFormQuestionsCompatView,
    AppraisalFormSetsCompatView,
    AppraisalCyclesCompatView,
    AppraisalsMyAssessmentsView,
    AppraisalsTeamEvaluationsView,
    AppraisalsByCycleCompatView,
    AppraisalsByEmployeeAndCycleCompatView,
    AppraisalsDetailCompatView,
    AppraisalsScoreBreakdownCompatView,
    AppraisalsFinalizeCompatView,
    KpiActiveCycleCompatView,
    KpiCategoryCompatView,
    KpiLibraryCompatView,
    KpiGoalSetCompatView,
    KpiGoalItemCompatView,
    KpiProgressCompatView,
    KpiRevisionCompatView,
    KpiScoreCompatView,
    KpiHistoryCompatView,
    KpiGoalSetAuditCompatView,
    KpiAuditOrgCompatView,
    KpiAuditTeamCompatView,
    KpiAuditEmployeeCompatView,
    MidcycleSummaryCompatView,
    KpiSummaryReportCompatView,
    KpiActualsCompletionReportCompatView,
    ReportDataCompatView,
    ReportDownloadCompatView,
    GenericListCompatView,
    TagsCompatView,
    FeedbacksCompatView,
    FeedbackManagerStatsCompatView,
    FeedbackEmployeeStatsCompatView,
    FeedbackRepliesCompatView,
    FeedbackPublishCompatView,
    MeetingsCompatView,
    MeetingsManagerStatsCompatView,
    MeetingsEmployeeStatsCompatView,
    MeetingsCommentsCompatView,
    MeetingsActionItemCompatView,
    MeetingsPublishCompatView,
    AuditLogsCompatView,
    AuditSummaryCompatView,
    AuditStatisticsCompatView,
    AuditEntityHistoryCompatView,
    AuditUserActivityCompatView,
    AuditLogsExportCompatView,
    PerformanceHistoryPulseCompatView,
    PerformanceHistoryAllCompatView,
    PerformanceHistoryMeetingPulseCompatView,
    PerformancePulseBenchmarksView,
    PerformancePulseGoalsOverlayView,
    PerformancePulseExportView,
    Feedback360GenericCompatView,
    AppraisalsApproveCompatView,
    AppraisalsPublishCompatView,
    AppraisalsCompatView,
    AppraisalsCalculateCompatView,
    AppraisalsSignOffCompatView,
    ManagerEvaluationFormCompatView,
    ManagerEvaluationAnswersCompatView,
    ManagerEvaluationDraftCompatView,
    ManagerEvaluationSubmitCompatView,
    SelfAssessmentFormCompatView,
    SelfAssessmentAnswersCompatView,
    SelfAssessmentDraftCompatView,
    SelfAssessmentSubmitCompatView,
)

urlpatterns = [
    # Dashboards
    re_path(r'^dashboard/manager/?$', ManagerDashboardView.as_view(), name='compat_dashboard_manager'),
    re_path(r'^dashboard/hr/?$', HrDashboardView.as_view(), name='compat_dashboard_hr'),
    re_path(r'^dashboard/admin/?$', AdminDashboardView.as_view(), name='compat_dashboard_admin'),
    re_path(r'^dashboard/employee/?$', EmployeeDashboardView.as_view(), name='compat_dashboard_employee'),

    # Departments
    re_path(r'^departments/active/?$', DepartmentCompatView.as_view(), {'pk': 'active'}, name='compat_departments_active'),
    re_path(r'^departments/(?P<pk>[^/]+)/members/?$', DepartmentMembersCompatView.as_view(), name='compat_departments_members'),
    re_path(r'^departments/(?P<pk>[^/]+)/headcount/?$', DepartmentHeadcountCompatView.as_view(), name='compat_departments_headcount'),
    re_path(r'^departments/(?P<pk>[^/]+)/?$', DepartmentCompatView.as_view(), name='compat_departments_detail'),
    re_path(r'^departments/?$', DepartmentCompatView.as_view(), name='compat_departments_list'),
    re_path(r'^org/departments/(?P<pk>[^/]+)/?$', DepartmentCompatView.as_view(), name='compat_org_dept_detail'),
    re_path(r'^org/departments/?$', DepartmentCompatView.as_view(), name='compat_org_departments'),
    re_path(r'^employee-departments/assign/?$', EmployeeDepartmentAssignCompatView.as_view(), name='compat_emp_dept_assign'),

    # Teams
    re_path(r'^teams/assign/?$', TeamAssignCompatView.as_view(), name='compat_teams_assign'),
    re_path(r'^teams/employee/(?P<employeeId>[^/]+)/?$', TeamEmployeeCompatView.as_view(), name='compat_teams_employee'),
    re_path(r'^teams/(?P<pk>[^/]+)/members/(?P<employeeId>[^/]+)/?$', TeamMembersCompatView.as_view(), name='compat_teams_member_detail'),
    re_path(r'^teams/(?P<pk>[^/]+)/members/?$', TeamMembersCompatView.as_view(), name='compat_teams_members'),
    re_path(r'^teams/(?P<pk>[^/]+)/?$', TeamCompatView.as_view(), name='compat_teams_detail'),
    re_path(r'^teams/?$', TeamCompatView.as_view(), name='compat_teams_list'),

    # Job Levels
    re_path(r'^job-levels/(?P<pk>[^/]+)/?$', JobLevelCompatView.as_view(), name='compat_job_levels_detail'),
    re_path(r'^job-levels/?$', JobLevelCompatView.as_view(), name='compat_job_levels_list'),

    # Positions
    re_path(r'^positions/(?P<pk>[^/]+)/?$', PositionCompatView.as_view(), name='compat_positions_detail'),
    re_path(r'^positions/?$', PositionCompatView.as_view(), name='compat_positions_list'),

    # Financial Years
    re_path(r'^financial-years/current/?$', FinancialYearCompatView.as_view(), {'pk': 'current'}, name='compat_financial_years_current'),
    re_path(r'^financial-years/rollover/?$', FinancialYearCompatView.as_view(), {'action': 'rollover'}, name='compat_financial_years_rollover'),
    re_path(r'^financial-years/(?P<pk>[^/]+)/set-current/?$', FinancialYearCompatView.as_view(), {'action': 'set-current'}, name='compat_financial_years_set_current'),
    re_path(r'^financial-years/(?P<pk>[^/]+)/deactivate/?$', FinancialYearCompatView.as_view(), {'action': 'deactivate'}, name='compat_financial_years_deactivate'),
    re_path(r'^financial-years/(?P<pk>[^/]+)/?$', FinancialYearCompatView.as_view(), name='compat_financial_years_detail'),
    re_path(r'^financial-years/?$', FinancialYearCompatView.as_view(), name='compat_financial_years_list'),

    # Performance Categories
    re_path(r'^performance-categories/(?P<pk>[^/]+)/?$', PerformanceCategoryCompatView.as_view(), name='compat_perf_categories_detail'),
    re_path(r'^performance-categories/?$', PerformanceCategoryCompatView.as_view(), name='compat_perf_categories_list'),

    # Roles & Role Assignments
    re_path(r'^roles/(?P<pk>[^/]+)/?$', RoleCompatView.as_view(), name='compat_roles_detail'),
    re_path(r'^roles/?$', RoleCompatView.as_view(), name='compat_roles_list'),
    re_path(r'^employees/(?P<employeeId>[^/]+)/roles/(?P<roleId>[^/]+)/?$', EmployeeRoleCompatView.as_view(), name='compat_emp_roles_detail'),
    re_path(r'^employees/(?P<employeeId>[^/]+)/roles/?$', EmployeeRoleCompatView.as_view(), name='compat_emp_roles_list'),

    # Permissions & Matrix
    re_path(r'^permissions/matrix/?$', PermissionMatrixCompatView.as_view(), name='compat_permissions_matrix'),
    re_path(r'^permissions/assign/toggle/?$', PermissionAssignCompatView.as_view(), {'action': 'toggle'}, name='compat_permissions_assign_toggle'),
    re_path(r'^permissions/assign/(?P<roleId>[^/]+)/(?P<levelId>[^/]+)/?$', PermissionAssignCompatView.as_view(), name='compat_permissions_assign_role_level'),
    re_path(r'^permissions/assign/(?P<pk>[^/]+)/?$', PermissionAssignCompatView.as_view(), name='compat_permissions_assign_delete'),
    re_path(r'^permissions/assign/?$', PermissionAssignCompatView.as_view(), name='compat_permissions_assign'),
    re_path(r'^permissions/(?P<pk>[^/]+)/?$', PermissionCompatView.as_view(), name='compat_permissions_detail'),
    re_path(r'^permissions/?$', PermissionCompatView.as_view(), name='compat_permissions_list'),

    # Employees
    re_path(r'^emp/all/?$', EmployeeAllCompatView.as_view(), name='compat_emp_all'),
    re_path(r'^emp/search/?$', EmployeeCompatView.as_view(), name='compat_emp_search'),
    re_path(r'^emp/me/profile/?$', CurrentUserProfileCompatView.as_view(), name='compat_emp_me_profile'),
    re_path(r'^emp/me/?$', CurrentUserProfileCompatView.as_view(), name='compat_emp_me'),
    re_path(r'^emp/(?P<pk>[^/]+)/profile/?$', CurrentUserProfileCompatView.as_view(), name='compat_emp_pk_profile'),
    re_path(r'^employees/me/profile/?$', CurrentUserProfileCompatView.as_view(), name='compat_employees_me_profile'),
    re_path(r'^employees/me/?$', CurrentUserProfileCompatView.as_view(), name='compat_employees_me'),
    re_path(r'^employees/(?P<pk>[^/]+)/profile/?$', CurrentUserProfileCompatView.as_view(), name='compat_employees_pk_profile'),
    re_path(r'^emp/(?P<pk>[^/]+)/activate/?$', EmployeeStatusToggleCompatView.as_view(), {'action': 'activate'}, name='compat_emp_activate'),
    re_path(r'^emp/(?P<pk>[^/]+)/deactivate/?$', EmployeeStatusToggleCompatView.as_view(), {'action': 'deactivate'}, name='compat_emp_deactivate'),
    re_path(r'^employees/(?P<pk>[^/]+)/activate/?$', EmployeeStatusToggleCompatView.as_view(), {'action': 'activate'}, name='compat_employees_activate'),
    re_path(r'^employees/(?P<pk>[^/]+)/deactivate/?$', EmployeeStatusToggleCompatView.as_view(), {'action': 'deactivate'}, name='compat_employees_deactivate'),
    re_path(r'^emp/(?P<pk>[^/]+)/direct-reports/?$', EmployeeDirectReportsCompatView.as_view(), name='compat_emp_direct_reports'),
    re_path(r'^emp/(?P<pk>[^/]+)/manager/?$', EmployeeManagerCompatView.as_view(), name='compat_emp_manager'),
    re_path(r'^emp/(?P<pk>[^/]+)/?$', EmployeeCompatView.as_view(), name='compat_emp_detail'),
    re_path(r'^emp/?$', EmployeeCompatView.as_view(), name='compat_emp_list'),
    re_path(r'^employees/(?P<pk>[^/]+)/?$', EmployeeCompatView.as_view(), name='compat_employees_detail'),
    re_path(r'^employees/?$', EmployeeCompatView.as_view(), name='compat_employees_list'),

    # Appraisals & Cycles
    re_path(r'^appraisal-cycles/active/?$', AppraisalCyclesCompatView.as_view(), {'pk': 'active'}, name='compat_cycles_active'),
    re_path(r'^appraisal-cycles/(?P<pk>[^/]+)/?$', AppraisalCyclesCompatView.as_view(), name='compat_cycles_detail'),
    re_path(r'^appraisal-cycles/?$', AppraisalCyclesCompatView.as_view(), name='compat_cycles_list'),

    re_path(r'^appraisals/my-assessments/?$', AppraisalsMyAssessmentsView.as_view(), name='compat_my_assessments'),
    re_path(r'^appraisals/team-evaluations/?$', AppraisalsTeamEvaluationsView.as_view(), name='compat_team_evaluations'),
    re_path(r'^appraisals/cycle/(?P<cycleId>[^/]+)/?$', AppraisalsByCycleCompatView.as_view(), name='compat_appraisals_by_cycle'),
    re_path(r'^appraisals/employee/(?P<employeeId>[^/]+)/cycle/(?P<cycleId>[^/]+)/?$', AppraisalsByEmployeeAndCycleCompatView.as_view(), name='compat_appraisal_employee_cycle'),
    re_path(r'^appraisals/(?P<pk>[^/]+)/score-breakdown/?$', AppraisalsScoreBreakdownCompatView.as_view(), name='compat_appraisal_score_breakdown'),
    re_path(r'^appraisals/(?P<pk>[^/]+)/finalize/?$', AppraisalsFinalizeCompatView.as_view(), name='compat_appraisal_finalize'),
    re_path(r'^appraisals/360/?$', AppraisalsDetailCompatView.as_view(), {'pk': '360'}, name='compat_appraisals_360'),
    re_path(r'^appraisals/(?P<pk>[^/]+)/approve/?$', AppraisalsApproveCompatView.as_view(), name='compat_appraisal_approve'),
    re_path(r'^appraisals/(?P<pk>[^/]+)/publish/?$', AppraisalsPublishCompatView.as_view(), name='compat_appraisal_publish'),
    re_path(r'^appraisals/(?P<pk>[^/]+)/calculate/?$', AppraisalsCalculateCompatView.as_view(), name='compat_appraisal_calculate'),
    re_path(r'^appraisals/(?P<pk>[^/]+)/employee-sign-off/?$', AppraisalsSignOffCompatView.as_view(), {'role': 'employee'}, name='compat_appraisal_emp_signoff'),
    re_path(r'^appraisals/(?P<pk>[^/]+)/manager-sign-off/?$', AppraisalsSignOffCompatView.as_view(), {'role': 'manager'}, name='compat_appraisal_mgr_signoff'),
    re_path(r'^appraisals/(?P<pk>[^/]+)/?$', AppraisalsDetailCompatView.as_view(), name='compat_appraisal_detail'),
    re_path(r'^appraisals/?$', AppraisalsCompatView.as_view(), name='compat_appraisals_list'),

    # Manager & Self Evaluations
    re_path(r'^manager-evaluations/form/(?P<pk>[^/]+)/?$', ManagerEvaluationFormCompatView.as_view(), name='compat_mgr_eval_form'),
    re_path(r'^manager-evaluations/(?P<pk>[^/]+)/answers/?$', ManagerEvaluationAnswersCompatView.as_view(), name='compat_mgr_eval_answers'),
    re_path(r'^manager-evaluations/(?P<pk>[^/]+)/draft/?$', ManagerEvaluationDraftCompatView.as_view(), name='compat_mgr_eval_draft'),
    re_path(r'^manager-evaluations/(?P<pk>[^/]+)/submit/?$', ManagerEvaluationSubmitCompatView.as_view(), name='compat_mgr_eval_submit'),

    re_path(r'^self-assessments/form/(?P<pk>[^/]+)/?$', SelfAssessmentFormCompatView.as_view(), name='compat_self_eval_form'),
    re_path(r'^self-assessments/(?P<pk>[^/]+)/answers/?$', SelfAssessmentAnswersCompatView.as_view(), name='compat_self_eval_answers'),
    re_path(r'^self-assessments/(?P<pk>[^/]+)/draft/?$', SelfAssessmentDraftCompatView.as_view(), name='compat_self_eval_draft'),
    re_path(r'^self-assessments/(?P<pk>[^/]+)/submit/?$', SelfAssessmentSubmitCompatView.as_view(), name='compat_self_eval_submit'),

    # Continuous Feedback & Tags
    re_path(r'^tags/(?P<pk>[^/]+)/?$', TagsCompatView.as_view(), name='compat_tags_detail'),
    re_path(r'^tags/?$', TagsCompatView.as_view(), name='compat_tags_list'),
    re_path(r'^feedbacks/manager/(?P<manager_id>[^/]+)/stats/?$', FeedbackManagerStatsCompatView.as_view(), name='compat_feedbacks_mgr_stats'),
    re_path(r'^feedbacks/employee/(?P<employee_id>[^/]+)/stats/?$', FeedbackEmployeeStatsCompatView.as_view(), name='compat_feedbacks_emp_stats'),
    re_path(r'^feedbacks/stats/(?P<employee_id>[^/]+)/?$', FeedbackEmployeeStatsCompatView.as_view(), name='compat_feedbacks_profile_stats'),
    re_path(r'^feedbacks/replies/(?P<reply_id>[^/]+)/?$', FeedbackRepliesCompatView.as_view(), name='compat_feedbacks_reply_detail'),
    re_path(r'^feedbacks/(?P<pk>[^/]+)/replies/?$', FeedbackRepliesCompatView.as_view(), name='compat_feedbacks_replies'),
    re_path(r'^feedbacks/(?P<pk>[^/]+)/comments/?$', FeedbackRepliesCompatView.as_view(), name='compat_feedbacks_comments'),
    re_path(r'^feedbacks/(?P<pk>[^/]+)/publish/?$', FeedbackPublishCompatView.as_view(), name='compat_feedbacks_publish'),
    re_path(r'^feedbacks/manager/(?P<manager_id>[^/]+)/?$', FeedbacksCompatView.as_view(), name='compat_feedbacks_mgr'),
    re_path(r'^feedbacks/employee/(?P<employee_id>[^/]+)/?$', FeedbacksCompatView.as_view(), name='compat_feedbacks_emp'),
    re_path(r'^feedbacks/(?P<pk>[^/]+)/?$', FeedbacksCompatView.as_view(), name='compat_feedbacks_detail'),
    re_path(r'^feedbacks/?$', FeedbacksCompatView.as_view(), name='compat_feedbacks_list'),

    # 1-on-1 Sync Meetings
    re_path(r'^meetings/manager/(?P<manager_id>[^/]+)/stats/?$', MeetingsManagerStatsCompatView.as_view(), name='compat_meetings_mgr_stats'),
    re_path(r'^meetings/employee/(?P<employee_id>[^/]+)/stats/?$', MeetingsEmployeeStatsCompatView.as_view(), name='compat_meetings_emp_stats'),
    re_path(r'^meetings/(?P<pk>[^/]+)/items/(?P<item_id>[^/]+)/status/?$', MeetingsActionItemCompatView.as_view(), name='compat_meetings_item_status'),
    re_path(r'^meetings/(?P<pk>[^/]+)/items/(?P<item_id>[^/]+)/reopen/?$', MeetingsActionItemCompatView.as_view(), name='compat_meetings_item_reopen'),
    re_path(r'^meetings/(?P<pk>[^/]+)/comments/?$', MeetingsCommentsCompatView.as_view(), name='compat_meetings_comments'),
    re_path(r'^meetings/(?P<pk>[^/]+)/publish/?$', MeetingsPublishCompatView.as_view(), name='compat_meetings_publish'),
    re_path(r'^meetings/manager/(?P<manager_id>[^/]+)/?$', MeetingsCompatView.as_view(), name='compat_meetings_mgr'),
    re_path(r'^meetings/employee/(?P<employee_id>[^/]+)/?$', MeetingsCompatView.as_view(), name='compat_meetings_emp'),
    re_path(r'^meetings/(?P<pk>[^/]+)/?$', MeetingsCompatView.as_view(), name='compat_meetings_detail'),
    re_path(r'^meetings/?$', MeetingsCompatView.as_view(), name='compat_meetings_list'),

    # Audit Logs
    re_path(r'^audit-logs/summary/?$', AuditSummaryCompatView.as_view(), name='compat_audit_summary'),
    re_path(r'^audit-logs/statistics/?$', AuditStatisticsCompatView.as_view(), name='compat_audit_statistics'),
    re_path(r'^audit-logs/entity/(?P<tableName>[^/]+)/(?P<recordId>[^/]+)/?$', AuditEntityHistoryCompatView.as_view(), name='compat_audit_entity'),
    re_path(r'^audit-logs/user/(?P<userId>[^/]+)/activity/?$', AuditUserActivityCompatView.as_view(), name='compat_audit_user_activity'),
    re_path(r'^audit-logs/export/csv/?$', AuditLogsExportCompatView.as_view(), {'fmt': 'csv'}, name='compat_audit_export_csv'),
    re_path(r'^audit-logs/export/pdf/?$', AuditLogsExportCompatView.as_view(), {'fmt': 'pdf'}, name='compat_audit_export_pdf'),
    re_path(r'^audit-logs/(?P<pk>[^/]+)/?$', AuditLogsCompatView.as_view(), name='compat_audit_detail'),
    re_path(r'^audit-logs/?$', AuditLogsCompatView.as_view(), name='compat_audit_list'),

    # Performance History & Pulse
    re_path(r'^performance-history/meeting-pulse/?$', PerformanceHistoryMeetingPulseCompatView.as_view(), name='compat_perf_meeting_pulse'),
    re_path(r'^performance-history/department-benchmarks/?$', PerformancePulseBenchmarksView.as_view(), name='compat_perf_benchmarks'),
    re_path(r'^performance-history/goals-overlay/?$', PerformancePulseGoalsOverlayView.as_view(), name='compat_perf_goals_overlay'),
    re_path(r'^performance-history/export/(?P<fmt>csv|pdf)/?$', PerformancePulseExportView.as_view(), name='compat_perf_export_fmt'),
    re_path(r'^performance-history/export/?$', PerformancePulseExportView.as_view(), name='compat_perf_export'),
    re_path(r'^performance-history/pulse/?$', PerformanceHistoryPulseCompatView.as_view(), name='compat_perf_pulse'),
    re_path(r'^performance-history/all/raw/?$', PerformanceHistoryPulseCompatView.as_view(), name='compat_perf_all_raw'),
    re_path(r'^performance-history/all/?$', PerformanceHistoryAllCompatView.as_view(), name='compat_perf_all'),
    re_path(r'^performance-history/employee/(?P<employee_id>[^/]+)/raw/?$', PerformanceHistoryPulseCompatView.as_view(), name='compat_perf_emp_raw'),
    re_path(r'^performance-history/employee/(?P<employee_id>[^/]+)/?$', PerformanceHistoryAllCompatView.as_view(), name='compat_perf_emp'),

    # KPI Categories
    re_path(r'^kpi/categories/paginated/?$', KpiCategoryCompatView.as_view(), name='compat_kpi_categories_paginated'),
    re_path(r'^kpi/categories/(?P<pk>[^/]+)/?$', KpiCategoryCompatView.as_view(), name='compat_kpi_categories_detail'),
    re_path(r'^kpi/categories/?$', KpiCategoryCompatView.as_view(), name='compat_kpi_categories'),

    # KPI Library
    re_path(r'^kpi/library/all/?$', KpiLibraryCompatView.as_view(), name='compat_kpi_library_all'),
    re_path(r'^kpi/library/import/?$', KpiLibraryCompatView.as_view(), name='compat_kpi_library_import'),
    re_path(r'^kpi/library/history/(?P<position_id>[^/]+)/?$', KpiLibraryCompatView.as_view(), name='compat_kpi_library_history'),
    re_path(r'^kpi/library/(?P<pk>[^/]+)/status/?$', KpiLibraryCompatView.as_view(), name='compat_kpi_library_status'),
    re_path(r'^kpi/library/(?P<pk>[^/]+)/toggle-history-status/?$', KpiLibraryCompatView.as_view(), name='compat_kpi_library_toggle_hist'),
    re_path(r'^kpi/library/(?P<pk>[^/]+)/?$', KpiLibraryCompatView.as_view(), name='compat_kpi_library_detail'),
    re_path(r'^kpi/library/?$', KpiLibraryCompatView.as_view(), name='compat_kpi_library_list'),

    # KPI Assignment & Goal Sets
    re_path(r'^kpi/assign/?$', KpiGoalSetCompatView.as_view(), name='compat_kpi_assign'),
    re_path(r'^kpi/bulk-assign/?$', KpiGoalSetCompatView.as_view(), name='compat_kpi_bulk_assign'),
    re_path(r'^kpi/approve/(?P<pk>[^/]+)/?$', KpiGoalSetCompatView.as_view(), name='compat_kpi_approve'),
    re_path(r'^kpi/goal-set/(?P<pk>[^/]+)/revert/?$', KpiGoalSetCompatView.as_view(), name='compat_kpi_revert'),
    re_path(r'^kpi/goal-set/(?P<pk>[^/]+)/lock/?$', KpiGoalSetCompatView.as_view(), name='compat_kpi_lock'),
    re_path(r'^kpi/goal-set/(?P<goal_set_id>[^/]+)/bulk-items/?$', KpiGoalItemCompatView.as_view(), name='compat_kpi_bulk_items'),
    re_path(r'^kpi/goal-set/(?P<goal_set_id>[^/]+)/items/?$', KpiGoalItemCompatView.as_view(), name='compat_kpi_goal_items'),
    re_path(r'^kpi/goal-set/employee/(?P<employee_id>[^/]+)/?$', KpiGoalSetCompatView.as_view(), name='compat_kpi_goal_set_emp'),
    re_path(r'^kpi/goal-set/team/?$', KpiGoalSetCompatView.as_view(), name='compat_kpi_goal_set_team'),
    re_path(r'^kpi/goal-set/department/?$', KpiGoalSetCompatView.as_view(), name='compat_kpi_goal_set_dept'),
    re_path(r'^kpi/goal-set/(?P<pk>[^/]+)/?$', KpiGoalSetCompatView.as_view(), name='compat_kpi_goal_set_detail'),

    # KPI Items, Progress, Revision, Scores
    re_path(r'^kpi/items/(?P<pk>[^/]+)/?$', KpiGoalItemCompatView.as_view(), name='compat_kpi_item_detail'),
    re_path(r'^kpi/progress/history/?$', KpiProgressCompatView.as_view(), name='compat_kpi_progress_history'),
    re_path(r'^kpi/progress/?$', KpiProgressCompatView.as_view(), name='compat_kpi_progress'),
    re_path(r'^kpi/revise/(?P<pk>[^/]+)/?$', KpiRevisionCompatView.as_view(), name='compat_kpi_revise'),
    re_path(r'^kpi/calculate-score/?$', KpiScoreCompatView.as_view(), name='compat_kpi_calculate_score'),
    re_path(r'^kpi/active-cycle/?$', KpiActiveCycleCompatView.as_view(), name='compat_kpi_active_cycle'),

    # Midcycle Summary & Transitions
    re_path(r'^kpi/midcycle/change/?$', MidcycleSummaryCompatView.as_view(), name='compat_kpi_midcycle_change'),
    re_path(r'^kpi/midcycle/(?P<employee_id>[^/]+)/(?P<cycle_id>[^/]+)/finalize/?$', MidcycleSummaryCompatView.as_view(), name='compat_kpi_midcycle_finalize'),
    re_path(r'^kpi/midcycle/(?P<employee_id>[^/]+)/(?P<cycle_id>[^/]+)/calculate/?$', MidcycleSummaryCompatView.as_view(), name='compat_kpi_midcycle_calculate'),
    re_path(r'^kpi/midcycle/(?P<employee_id>[^/]+)/(?P<cycle_id>[^/]+)/?$', MidcycleSummaryCompatView.as_view(), name='compat_kpi_midcycle_summary'),

    # KPI History & Audit Trails
    re_path(r'^kpi-history/employee/(?P<employee_id>[^/]+)/?$', KpiHistoryCompatView.as_view(), name='compat_kpi_history_emp'),
    re_path(r'^kpi-history/goal-set/(?P<pk>[^/]+)/audit/?$', KpiGoalSetAuditCompatView.as_view(), name='compat_kpi_goalset_audit'),
    re_path(r'^kpi-audit/org/?$', KpiAuditOrgCompatView.as_view(), name='compat_kpi_audit_org'),
    re_path(r'^kpi-audit/team/?$', KpiAuditTeamCompatView.as_view(), name='compat_kpi_audit_team'),
    re_path(r'^kpi-audit/employee/(?P<pk>[^/]+)/?$', KpiAuditEmployeeCompatView.as_view(), name='compat_kpi_audit_employee'),

    # Reports
    re_path(r'^(?:v1/)?reports/kpi-summary/?$', KpiSummaryReportCompatView.as_view(), name='compat_reports_kpi_summary'),
    re_path(r'^(?:v1/)?reports/kpi-actuals-completion/?$', KpiActualsCompletionReportCompatView.as_view(), name='compat_reports_kpi_actuals'),
    re_path(r'^(?:v1/)?reports/(?P<endpoint>[^/]+)/download/?$', ReportDownloadCompatView.as_view(), name='compat_reports_download'),
    re_path(r'^(?:v1/)?reports/(?P<endpoint>[^/]+)/?$', ReportDataCompatView.as_view(), name='compat_reports_data'),

    # 360 Feedback & Secondary Hubs
    re_path(r'^360-feedback/.*$', Feedback360GenericCompatView.as_view(), name='compat_360_feedback'),
    re_path(r'^feedback/.*$', Feedback360GenericCompatView.as_view(), name='compat_feedback_360'),
    re_path(r'^scoring-policy.*$', Feedback360GenericCompatView.as_view(), name='compat_scoring_policy'),
    re_path(r'^competency.*$', Feedback360GenericCompatView.as_view(), name='compat_competency'),
    re_path(r'^calibration/.*$', Feedback360GenericCompatView.as_view(), name='compat_calibration'),

    # Appraisal Forms & Form Sets (Form Template Builder)
    re_path(r'^appraisal-forms/(?P<form_id>[^/]+)/categories/?$', AppraisalFormCategoriesCompatView.as_view(), name='compat_form_categories'),
    re_path(r'^appraisal-forms/categories/(?P<cat_id>[^/]+)/questions/?$', AppraisalFormQuestionsCompatView.as_view(), name='compat_category_questions'),
    re_path(r'^appraisal-forms/(?P<pk>[^/]+)/?$', AppraisalFormDetailCompatView.as_view(), name='compat_form_detail'),
    re_path(r'^appraisal-forms/?$', AppraisalFormsCompatView.as_view(), name='compat_forms_list'),
    re_path(r'^appraisal-form-sets/cycle/(?P<cycle_id>[^/]+)/?$', AppraisalFormSetsCompatView.as_view(), name='compat_form_sets_cycle'),
    re_path(r'^appraisal-form-sets/(?P<pk>[^/]+)/?$', AppraisalFormSetsCompatView.as_view(), name='compat_form_sets_detail'),
    re_path(r'^appraisal-form-sets/?$', AppraisalFormSetsCompatView.as_view(), name='compat_form_sets_list'),

    # Fallback configuration routes for other navigation items
    re_path(r'^categories.*$', GenericListCompatView.as_view()),
    re_path(r'^kpi/.*$', GenericListCompatView.as_view()),
    re_path(r'^pip/.*$', GenericListCompatView.as_view()),
    re_path(r'^idp/.*$', GenericListCompatView.as_view()),
]
