# Generated by Django 4.2.27 on 2026-09-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employeeprofile_birth_place_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
